chore: update sidebar links
loopbackio/explorer.loopback.io pull request #8
Opened 2020-01-20 04:07 UTC by achrinza

2020-01-20 04:08 UTC, achrinza commented
Commit Linter seems to be chocking on the commit sign-off.

2020-01-24 02:15 UTC, dhmlau commented
@achrinza, the commit linter was complaining about:
```
**************************************************
**
**  Linting commit logs
**
**  1 problems found:
**    730fce6 - chore: update sidebar links: line 3 longer than 72 characters.
**
**************************************************
```

2020-01-24 02:16 UTC, achrinza commented
@dhmlau Line 3 is the commit sign-off which I believe is required for the DCO check.

See https://github.com/strongloop/loopback-next/issues/4492

2020-01-24 13:29 UTC, dhmlau commented
Not sure if the "line 3" it complains about is the blank line or the DCO sign off message, the DCO message indeed has more than 72 characters. 
@strongloop/loopback-maintainers, since the max number of characters for LB4 commits is 100 (see https://loopback.io/doc/en/lb4/code-contrib-lb4.html#body), does it make sense to relax this limit? Thanks.

2020-01-24 15:10 UTC, dhmlau commented
Discussed with @bajtos, since there won't be much updates in this repo, we can force merge the PR with the commit linter error when it's ready.

2020-01-24 15:12 UTC, dhmlau requested changes
@achrinza, thanks for updating the html not using v4.loopback.io.  I noticed there are other references of `v4.loopback.io`.  Since you're updating it, could you please also take care of those too? Thanks.

2020-01-24 15:12 UTC, dhmlau commented on index.loopback.html
> +              <img src="https://loopback.io/img/global/loopback-mark-frame-white.svg" width=40px/>
It seems to be a broken link for the svg.

2020-01-24 15:12 UTC, dhmlau commented on index.loopback.html
> +                  <a href="https://loopback.io/doc/en/lb4/Examples-and-tutorials.html">Tutorials</a>
This link no longer exist. At some point, we split the examples and tutorials into 2 pages, i.e. 
https://loopback.io/doc/en/lb4/Tutorials.html
https://loopback.io/doc/en/lb4/Examples.html

2020-02-07 13:36 UTC, achrinza commented
@dhmlau Everything should be fixed

2020-02-07 15:33 UTC, dhmlau approved these changes

2020-02-07 15:34 UTC, dhmlau commented
Thanks @achrinza! I'm going to force merge it because the commit linter is due to the DCO signing message.

2020-02-07 15:34 UTC, merged